version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - --tracing=true
      - --tracing.zipkin=true
      - --tracing.zipkin.httpEndpoint=http://oc-collector:9411/api/v2/spans
      - --tracing.zipkin.sameSpan=true
      - --tracing.zipkin.id128Bit=true
      - --tracing.zipkin.sampleRate=1
      - --accesslog=true # output log to stdout
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  saga-purchase:
    image: minghsu0107/saga-purchase:latest
    restart: always
    environment:
      GIN_MODE: "release"
      NATS_CLUSTER_ID: "test-cluster"
      NATS_URL: "nats://nats-streaming:4222"
      # RPC_AUTH_SVC_HOST: "saga-account:8000" # using client LB
      RPC_AUTH_SVC_HOST: "reverse-proxy:80" # using traefik L4 LB
      RPC_PRODUCT_SVC_HOST: "reverse-proxy:80"
      OC_AGENT_HOST: "oc-collector:55678"
    depends_on:
      - nats-streaming
      - saga-account
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saga-purchase.rule=PathPrefix(`/api/purchase`)"
      - "traefik.http.routers.saga-purchase.entrypoints=web"
      - "traefik.http.routers.saga-purchase.service=saga-purchase"
      - "traefik.http.services.saga-purchase.loadbalancer.server.port=80"
  saga-account:
    image: minghsu0107/saga-account:latest
    restart: always
    environment:
      GIN_MODE: "release"
      DB_DSN: "ming:password@tcp(accountdb:3306)/account?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_ADDRS: "redis-node1:7000,redis-node1:7001,redis-node1:7002,redis-node1:7003,redis-node1:7004,redis-node1:7005"
      REDIS_PASSWORD: ${REDIS_PASSWD}
      JWT_ACCESS_TOKEN_EXPIRE_SECOND: "10800"
      JWT_REFRESH_TOKEN_EXPIRE_SECOND: "86400"
      OC_AGENT_HOST: "oc-collector:55678"
    depends_on:
      - accountdb
      - redis-cluster-creator
    expose:
      - "80"
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saga-account-http.rule=PathPrefix(`/api/auth`) || PathPrefix(`/api/info`)"
      - "traefik.http.routers.saga-account-http.entrypoints=web"
      - "traefik.http.routers.saga-account-http.service=saga-account-http"
      - "traefik.http.services.saga-account-http.loadbalancer.server.port=80"
      - "traefik.http.routers.saga-account-grpc.rule=Headers(`content-type`,`application/grpc`) && Headers(`service-name`, `auth.AuthService`)"
      - "traefik.http.routers.saga-account-grpc.entrypoints=web"
      - "traefik.http.routers.saga-account-grpc.service=saga-account-grpc"
      - "traefik.http.services.saga-account-grpc.loadbalancer.server.port=8000"
      - "traefik.http.services.saga-account-grpc.loadbalancer.server.scheme=h2c"
  saga-product:
    image: minghsu0107/saga-product:latest
    restart: always
    environment:
      APP: "product"
      GIN_MODE: "release"
      DB_DSN: "ming:password@tcp(productdb:3306)/product?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_ADDRS: "redis-node1:7000,redis-node1:7001,redis-node1:7002,redis-node1:7003,redis-node1:7004,redis-node1:7005"
      REDIS_PASSWORD: ${REDIS_PASSWD}
      NATS_CLUSTER_ID: "test-cluster"
      NATS_URL: "nats://nats-streaming:4222"
      NATS_QUEUE_GROUP: "product-queue"
      NATS_DURABLE_NAME: "product-durable"
      OC_AGENT_HOST: "oc-collector:55678"
    depends_on:
      - productdb
      - redis-cluster-creator
    expose:
      - "80"
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saga-product-http.rule=PathPrefix(`/api/product`) || PathPrefix(`/api/products`)"
      - "traefik.http.routers.saga-product-http.entrypoints=web"
      - "traefik.http.routers.saga-product-http.service=saga-product-http"
      - "traefik.http.services.saga-product-http.loadbalancer.server.port=80"
      - "traefik.http.routers.saga-product-grpc.rule=Headers(`content-type`,`application/grpc`) && Headers(`service-name`, `product.ProductService`)"
      - "traefik.http.routers.saga-product-grpc.entrypoints=web"
      - "traefik.http.routers.saga-product-grpc.service=saga-product-grpc"
      - "traefik.http.services.saga-product-grpc.loadbalancer.server.port=8000"
      - "traefik.http.services.saga-product-grpc.loadbalancer.server.scheme=h2c"
  saga-order:
    image: minghsu0107/saga-product:latest
    restart: always
    environment:
      APP: "order"
      GIN_MODE: "release"
      DB_DSN: "ming:password@tcp(orderdb:3306)/order?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_ADDRS: "redis-node1:7000,redis-node1:7001,redis-node1:7002,redis-node1:7003,redis-node1:7004,redis-node1:7005"
      REDIS_PASSWORD: ${REDIS_PASSWD}
      NATS_CLUSTER_ID: "test-cluster"
      NATS_URL: "nats://nats-streaming:4222"
      NATS_QUEUE_GROUP: "order-queue"
      NATS_DURABLE_NAME: "order-durable"
      RPC_AUTH_SVC_HOST: "reverse-proxy:80"
      RPC_PRODUCT_SVC_HOST: "reverse-proxy:80"
      OC_AGENT_HOST: "oc-collector:55678"
    depends_on:
      - orderdb
      - saga-account
      - saga-product
      - redis-cluster-creator
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saga-order-http.rule=PathPrefix(`/api/order`)"
      - "traefik.http.routers.saga-order-http.entrypoints=web"
      - "traefik.http.routers.saga-order-http.service=saga-order-http"
      - "traefik.http.services.saga-order-http.loadbalancer.server.port=80"
  saga-payment:
    image: minghsu0107/saga-product:latest
    restart: always
    environment:
      APP: "payment"
      GIN_MODE: "release"
      DB_DSN: "ming:password@tcp(paymentdb:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_ADDRS: "redis-node1:7000,redis-node1:7001,redis-node1:7002,redis-node1:7003,redis-node1:7004,redis-node1:7005"
      REDIS_PASSWORD: ${REDIS_PASSWD}
      NATS_CLUSTER_ID: "test-cluster"
      NATS_URL: "nats://nats-streaming:4222"
      NATS_QUEUE_GROUP: "payment-queue"
      NATS_DURABLE_NAME: "payment-durable"
      RPC_AUTH_SVC_HOST: "reverse-proxy:80"
      OC_AGENT_HOST: "oc-collector:55678"
    depends_on:
      - paymentdb
      - saga-account
      - redis-cluster-creator
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saga-payment-http.rule=PathPrefix(`/api/payment`)"
      - "traefik.http.routers.saga-payment-http.entrypoints=web"
      - "traefik.http.routers.saga-payment-http.service=saga-payment-http"
      - "traefik.http.services.saga-payment-http.loadbalancer.server.port=80"
  saga-orchestrator:
    image: minghsu0107/saga-product:latest
    restart: always
    environment:
      APP: "orchestrator"
      NATS_CLUSTER_ID: "test-cluster"
      NATS_URL: "nats://nats-streaming:4222"
      NATS_QUEUE_GROUP: "orchestrator-queue"
      NATS_DURABLE_NAME: "orchestrator-durable"
      OC_AGENT_HOST: "oc-collector:55678"
  nats-streaming:
    image: nats-streaming:0.11.2
    restart: unless-stopped
    ports:
      - 4222:4222
  prometheus:
    image: prom/prometheus:v2.25.2
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
  accountdb:
    image: mysql:8.0
    environment:
      MYSQL_USER: ming
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: account
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --max_allowed_packet=128M
      - --max-connections=10000 # default: 151
    ports:
      - 3306:3306
    volumes:
      - mysql_data_account:/var/lib/mysql
  productdb:
    image: mysql:8.0
    environment:
      MYSQL_USER: ming
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --max_allowed_packet=128M
      - --max-connections=10000
    ports:
      - 3307:3306
    volumes:
      - mysql_data_product:/var/lib/mysql
  orderdb:
    image: mysql:8.0
    environment:
      MYSQL_USER: ming
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --max_allowed_packet=128M
      - --max-connections=10000
    ports:
      - 3308:3306
    volumes:
      - mysql_data_order:/var/lib/mysql
  paymentdb:
    image: mysql:8.0
    environment:
      MYSQL_USER: ming
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --max_allowed_packet=128M
      - --max-connections=10000
    ports:
      - 3309:3306
    volumes:
      - mysql_data_payment:/var/lib/mysql
  jaeger:
    image: jaegertracing/all-in-one:1.22
    ports:
      - 14268:14268
      - 16686:16686
  oc-collector:
    image: omnition/opencensus-collector:0.1.10
    command:
      - --config=/conf/occollector-config.yaml
    ports:
      - 55678:55678
    volumes:
      - ./occollector/occollector-config.yaml:/conf/occollector-config.yaml
  redis-node1:
    build:
      context: redis
    ports:
      - 7000:7000
      - 17000:17000
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7000", --cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
  redis-node2:
    build:
      context: redis
    ports:
      - 7001:7001
      - 17001:17001
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7001",--cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
  redis-node3:
    build:
      context: redis
    ports:
      - 7002:7002
      - 17002:17002
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7002",--cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
  redis-node4:
    build:
      context: redis
    ports:
      - 7003:7003
      - 17003:17003
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7003",--cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node5:
    build:
      context: redis
    ports:
      - 7004:7004
      - 17004:17004
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7004",--cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node6:
    build:
      context: redis
    ports:
      - 7005:7005
      - 17005:17005
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7005",--cluster-announce-ip,"${REDIS_CLUSTER_IP}"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-cluster-creator:
    image: redis:5.0.1-alpine
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli -a ${REDIS_PASSWD} --cluster create ${REDIS_CLUSTER_IP}:7000 ${REDIS_CLUSTER_IP}:7001 ${REDIS_CLUSTER_IP}:7002 ${REDIS_CLUSTER_IP}:7003 ${REDIS_CLUSTER_IP}:7004 ${REDIS_CLUSTER_IP}:7005 --cluster-replicas 1']
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

volumes:
  mysql_data_account:
  mysql_data_product:
  mysql_data_order:
  mysql_data_payment: