global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.=
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'purchase_monitor'
    static_configs:
    - targets: ['saga-example_saga-purchase_1:8080', 'saga-example_saga-purchase_2:8080']
  - job_name: 'account_monitor'
    static_configs:
    - targets: ['saga-example_saga-account_1:8080','saga-example_saga-account_2:8080','saga-example_saga-account_3:8080']
  - job_name: 'product_monitor'
    static_configs:
    - targets: ['saga-example_saga-product_1:8080','saga-example_saga-product_2:8080']
  - job_name: 'order_monitor'
    static_configs:
    - targets: ['saga-example_saga-order_1:8080','saga-example_saga-order_2:8080']
  - job_name: 'payment_monitor'
    static_configs:
    - targets: ['saga-example_saga-payment_1:8080','saga-example_saga-payment_2:8080']
  - job_name: 'orchestrator_monitor'
    static_configs:
    - targets: ['saga-example_saga-orchestrator_1:8080', 'saga-example_saga-orchestrator_2:8080']