receivers:
  opencensus:
    port: 55678
  zipkin:
    port: 9411
  jaeger:
    jaeger-thrift-http-port: 14268
queued-exporters:
  my-jaeger-collector:
    # indicates whether queue processor should retry span batches in case of processing failure
    retry-on-failure: true
    sender-type: jaeger-thrift-http
    jaeger-thrift-http:
      collector-endpoint: http://jaeger:14268/api/traces
      timeout: 5s