receivers:
  opencensus:
    port: 55678
    # Changes the maximum msg size that can be received (default is 4MiB)
    max-recv-msg-size-mib: 32
    # Limits the maximum number of concurrent streams for each receiver transport (default is 100)
    max-concurrent-streams: 50
    # for helping load-balancing
    keepalive:
      server-parameters:
        # the amount of time after which an idle connection would be closed
        max-connection-idle: 90s
        # # max-connection-age is the maximum amount of time a connection may exist before it is closed
        max-connection-age: 180s
        max-connection-age-grace: 10s
        # time is a duration for which, if the server doesn't see any activity it pings the client to see
        # if the transport is still alive. The default is 2 hours.
        time: 30s
        # timeout is the wait time after a ping that the server waits for the response before closing the
        # connection. The default is 20 seconds.
        timeout: 5s
  zipkin:
    port: 9411
  jaeger:
    jaeger-thrift-http-port: 14268
queued-exporters:
  my-jaeger-collector:
    # the number of queue workers that will be dequeuing batches and sending them out (default is 10)
    num-workers: 4
    # default is 5000
    queue-size: 100
    # indicates whether queue processor should retry span batches in case of processing failure
    retry-on-failure: true
    sender-type: jaeger-thrift-http
    jaeger-thrift-http:
      collector-endpoint: http://jaeger:14268/api/traces
      timeout: 5s